
services:

  database:
    image: postgres:13-alpine
    container_name: bingo-db
    restart: always
    ports:
        - "5433:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
     
      - postgres-data:/var/lib/postgresql/data


  backend:
    container_name: bingo-backend
    
    build: .
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: "postgresql://johndoe:randompassword@database:5432/mydb?schema=public"
    depends_on:
      - database

  frontend:
    container_name: bingo-frontend
    build:
      context: ../front-end
    ports:
      - "8080:80" 
    depends_on:
      - backend

volumes:
  postgres-data: